### ISSUE TITLE
Error while starting app.py file

### ISSUE THREAD

**Issue by lokeshpanwar1** [Arif-Helmsys/Pyinsta#2]
PS C:\Users\****\Downloads\Pyinsta-main\Pyinsta-main> python app.py
Traceback (most recent call last):
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\app.py", line 7, in <module>
    from PyInsta import (Instagram, Console, Bruter, MultiAccount)
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\__init__.py", line 1, in <module>
    from .instagram import Instagram
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\instagram.py", line 7, in <module>
    from .libs import(URL_Shortened,LinkParser)
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\libs\__init__.py", line 1, in <module>
    from .url_shorter import *
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\libs\url_shorter.py", line 2, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by Helmssyss** [comment]
Its my fault.
write this code in console pip install beautifulsoup4==4.9.3


Btw i should also mention that I am not developing this tool anymore, if there are problems, of course I will try to solve them.

**Comment by lokeshpanwar1** [comment]
PS C:\Users\****\****\Pyinsta-main\Pyinsta-main> python app.py -h
Traceback (most recent call last):
  File "C:\Users\****\****s\Pyinsta-main\Pyinsta-main\app.py", line 7, in <module>
    from PyInsta import (Instagram, Console, Bruter, MultiAccount)
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\__init__.py", line 1, in <module>
    from .instagram import Instagram
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\instagram.py", line 7, in <module>
    from .libs import(URL_Shortened,LinkParser)
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\libs\__init__.py", line 2, in <module>
    from .multi_account import *
  File "C:\Users\****\****\Pyinsta-main\Pyinsta-main\PyInsta\libs\multi_account.py", line 11, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'


PS C:\Users\****\****\Pyinsta-main\Pyinsta-main> > python app.py -u finsoc.nsut -p Finsoc123
> : The term '>' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ > python app.py -u **** -p Gamer123
+ ~
    + CategoryInfo          : ObjectNotFound: (>:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException



Meanwhile I installed beautifulsoup4==4.9.3 but still facing same issue

**Comment by Helmssyss** [comment]
Its my fault again :D
pip install aiohttp==3.8.3

If you pay attention, you made a mistake while typing. You started typing with the ">" sign in the console. delete it and try it.

If you get `ModuleNotFoundError` you can download it with` pip install module_name.`

**Comment by lokeshpanwar1** [comment]
Ya I corrected it but still facing same issue


Successfully installed aiohttp-3.8.3 aiosignal-1.3.1 async-timeout-4.0.2 attrs-23.1.0 frozenlist-1.3.3 multidict-6.0.4 yarl-1.9.2
PS C:\Users******\Pyinsta-main\Pyinsta-main> python app.py -u ******* -p *****
Traceback (most recent call last):
  File "C:\User*****\Pyinsta-main\Pyinsta-main\app.py", line 7, in <module>
    from PyInsta import (Instagram, Console, Bruter, MultiAccount)
  File "C:\Users\******\Pyinsta-main\Pyinsta-main\PyInsta\__init__.py", line 1, in <module>
    from .instagram import Instagram
  File "C:\User*******\Pyinsta-main\Pyinsta-main\PyInsta\instagram.py", line 7, in <module>
    from .libs import(URL_Shortened,LinkParser)
  File "C:\User*******\Pyinsta-main\Pyinsta-main\PyInsta\libs\__init__.py", line 5, in <module>
    from .users import AllUsers
  File "C:\Users*****s\Pyinsta-main\Pyinsta-main\PyInsta\libs\users.py", line 1, in <module>
    import aiosqlite
ModuleNotFoundError: No module named 'aiosqlite'
PS C:\Users*****\Pyinsta-main\Pyinsta-main> python app.py -u ****** -p *****.txt
Traceback (most recent call last):
  File "C:\Users\*****\Pyinsta-main\Pyinsta-main\app.py", line 7, in <module>
    from PyInsta import (Instagram, Console, Bruter, MultiAccount)
  File "C:\User******\Pyinsta-main\Pyinsta-main\PyInsta\__init__.py", line 1, in <module>
    from .instagram import Instagram
  File "C:\Users******s\Pyinsta-main\Pyinsta-main\PyInsta\instagram.py", line 7, in <module>
    from .libs import(URL_Shortened,LinkParser)
  File "C:\Users*****\Pyinsta-main\Pyinsta-main\PyInsta\libs\__init__.py", line 5, in <module>
    from .users import AllUsers
  File "C:\Use*****\Pyinsta-main\Pyinsta-main\PyInsta\libs\users.py", line 1, in <module>
    import aiosqlite
ModuleNotFoundError: No module named 'aiosqlite'

**Comment by lokeshpanwar1** [comment]
Do I have to use .txt file or have to type name manually in the password section

**Comment by Helmssyss** [comment]
These module errors are caused by trying something and not updating the code properly. Download modules you don't have is no problem. 

If you are going to enter your own account, you will write manually.

**Comment by SpiritGun91** [comment]
![Screenshot_20230712-135541_crDroid Home](https://github.com/Helmssyss/Pyinsta/assets/101740573/03b8e38e-cb6a-4005-bdd1-bdc11208abcf)
Doesn't work on python 3.11
